### ISSUE TITLE
on android build the plugin change my .gradle files

### ISSUE THREAD

**Issue by TsankovRosen** [bamlab/fastlane-plugin-cordova#21] opened 2017-11-30 14:47 UTC
I am doing a little PoC and I found the fallowing problem:

When I do a very simple build of my application with this lane

platform :android do
  lane :poc do
    cordova(
      release:false, 
      platform:'android'
    )
  end
end

(build succeeded)

the plugin changes 2 of my .gradle files and the result is invalid .apk file.

**Comment by janpio** [comment] 2017-11-30 14:51
What files exactly does it change?
What are the changes?

**Comment by TsankovRosen** [comment] 2017-11-30 14:53
files are:

settings.gradle
build.gradle

I can't tell you much lets say I have more includes in settings.gradle and after the build they are not there.

**Comment by janpio** [comment] 2017-11-30 15:37
Does the same thing happen if you build manually with `cordova build android ...` (or prepare + compile) command (it is output during the build process when running the action from this plugin)?
If so, this is nothing caused by this plugin but just how the Cordova build process works.

**Comment by TsankovRosen** [comment] 2017-11-30 15:38
no, it happens only with fastlane

**Comment by janpio** [comment] 2017-11-30 15:59
If you think this should not happen, you can report the issue at issues.cordova.io - maybe something can be done about it.

Please also close this issue here. Thanks.

**Closed** 2017-12-01 07:59 UTC
